version: "3.8"

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: EduPlatform
      POSTGRES_USER: EduPlatform
      POSTGRES_PASSWORD: "1111"
    ports:
      - "5433:5432"
    volumes:
      - eduplatform_db_data:/var/lib/postgresql/data

  app:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: EduPlatform
      DB_PASSWORD: "1111"
      DB_NAME: EduPlatform
      DB_PORT: 5432
      NODE_ENV: development
    stdin_open: true
    tty: true

volumes:
  eduplatform_db_data:
    driver: local